// Fichier généré par scripts/gen-country-flag-index.ts — ne pas modifier à la main.
export interface FlagCountry {
  iso2: string;
  name: string;
}

export const FLAG_COUNTRIES: readonly FlagCountry[] = [
  { iso2: "ZA", name: "Afrique du Sud" },
  { iso2: "AL", name: "Albanie" },
  { iso2: "DZ", name: "Algérie" },
  { iso2: "DE", name: "Allemagne" },
  { iso2: "AO", name: "Angola" },
  { iso2: "SA", name: "Arabie saoudite" },
  { iso2: "AR", name: "Argentine" },
  { iso2: "AM", name: "Arménie" },
  { iso2: "AT", name: "Autriche" },
  { iso2: "AZ", name: "Azerbaïdjan" },
  { iso2: "BE", name: "Belgique" },
  { iso2: "BJ", name: "Bénin" },
  { iso2: "BY", name: "Biélorussie" },
  { iso2: "BO", name: "Bolivie" },
  { iso2: "BA", name: "Bosnie-Herzégovine" },
  { iso2: "BW", name: "Botswana" },
  { iso2: "BR", name: "Brésil" },
  { iso2: "BN", name: "Brunei" },
  { iso2: "BG", name: "Bulgarie" },
  { iso2: "BF", name: "Burkina Faso" },
  { iso2: "BI", name: "Burundi" },
  { iso2: "KH", name: "Cambodge" },
  { iso2: "CM", name: "Cameroun" },
  { iso2: "CL", name: "Chili" },
  { iso2: "CN", name: "Chine" },
  { iso2: "CY", name: "Chypre" },
  { iso2: "CO", name: "Colombie" },
  { iso2: "KP", name: "Corée du Nord" },
  { iso2: "KR", name: "Corée du Sud" },
  { iso2: "CI", name: "Côte d'Ivoire" },
  { iso2: "HR", name: "Croatie" },
  { iso2: "DK", name: "Danemark" },
  { iso2: "DJ", name: "Djibouti" },
  { iso2: "EG", name: "Égypte" },
  { iso2: "AE", name: "Émirats arabes unis" },
  { iso2: "EC", name: "Équateur" },
  { iso2: "ER", name: "Érythrée" },
  { iso2: "ES", name: "Espagne" },
  { iso2: "EE", name: "Estonie" },
  { iso2: "SZ", name: "Eswatini" },
  { iso2: "ET", name: "Éthiopie" },
  { iso2: "FI", name: "Finlande" },
  { iso2: "FR", name: "France" },
  { iso2: "GA", name: "Gabon" },
  { iso2: "GM", name: "Gambie" },
  { iso2: "GE", name: "Géorgie" },
  { iso2: "GH", name: "Ghana" },
  { iso2: "GR", name: "Grèce" },
  { iso2: "GN", name: "Guinée" },
  { iso2: "GQ", name: "Guinée équatoriale" },
  { iso2: "GW", name: "Guinée-Bissau" },
  { iso2: "GY", name: "Guyana" },
  { iso2: "GF", name: "Guyane française" },
  { iso2: "HU", name: "Hongrie" },
  { iso2: "ID", name: "Indonésie" },
  { iso2: "IQ", name: "Irak" },
  { iso2: "IR", name: "Iran" },
  { iso2: "IE", name: "Irlande" },
  { iso2: "IS", name: "Islande" },
  { iso2: "IL", name: "Israël" },
  { iso2: "IT", name: "Italie" },
  { iso2: "JP", name: "Japon" },
  { iso2: "JO", name: "Jordanie" },
  { iso2: "KE", name: "Kenya" },
  { iso2: "XK", name: "Kosovo" },
  { iso2: "KW", name: "Koweït" },
  { iso2: "LA", name: "Laos" },
  { iso2: "LS", name: "Lesotho" },
  { iso2: "LV", name: "Lettonie" },
  { iso2: "LB", name: "Liban" },
  { iso2: "LR", name: "Liberia" },
  { iso2: "LY", name: "Libye" },
  { iso2: "LT", name: "Lituanie" },
  { iso2: "LU", name: "Luxembourg" },
  { iso2: "MK", name: "Macédoine du Nord" },
  { iso2: "MG", name: "Madagascar" },
  { iso2: "MY", name: "Malaisie" },
  { iso2: "MW", name: "Malawi" },
  { iso2: "ML", name: "Mali" },
  { iso2: "MT", name: "Malte" },
  { iso2: "MA", name: "Maroc" },
  { iso2: "MR", name: "Mauritanie" },
  { iso2: "MD", name: "Moldavie" },
  { iso2: "MN", name: "Mongolie" },
  { iso2: "ME", name: "Monténégro" },
  { iso2: "MZ", name: "Mozambique" },
  { iso2: "MM", name: "Myanmar" },
  { iso2: "NA", name: "Namibie" },
  { iso2: "NE", name: "Niger" },
  { iso2: "NG", name: "Nigeria" },
  { iso2: "NO", name: "Norvège" },
  { iso2: "OM", name: "Oman" },
  { iso2: "UG", name: "Ouganda" },
  { iso2: "PS", name: "Palestine" },
  { iso2: "PY", name: "Paraguay" },
  { iso2: "NL", name: "Pays-Bas" },
  { iso2: "PE", name: "Pérou" },
  { iso2: "PH", name: "Philippines" },
  { iso2: "PL", name: "Pologne" },
  { iso2: "PT", name: "Portugal" },
  { iso2: "QA", name: "Qatar" },
  { iso2: "CF", name: "République centrafricaine" },
  { iso2: "CD", name: "République démocratique du Congo" },
  { iso2: "CG", name: "République du Congo" },
  { iso2: "RO", name: "Roumanie" },
  { iso2: "GB", name: "Royaume-Uni" },
  { iso2: "RU", name: "Russie" },
  { iso2: "RW", name: "Rwanda" },
  { iso2: "EH", name: "Sahara occidental" },
  { iso2: "SN", name: "Sénégal" },
  { iso2: "RS", name: "Serbie" },
  { iso2: "SL", name: "Sierra Leone" },
  { iso2: "SK", name: "Slovaquie" },
  { iso2: "SI", name: "Slovénie" },
  { iso2: "SO", name: "Somalie" },
  { iso2: "SD", name: "Soudan" },
  { iso2: "SS", name: "Soudan du Sud" },
  { iso2: "SE", name: "Suède" },
  { iso2: "CH", name: "Suisse" },
  { iso2: "SR", name: "Suriname" },
  { iso2: "SY", name: "Syrie" },
  { iso2: "TW", name: "Taïwan" },
  { iso2: "TZ", name: "Tanzanie" },
  { iso2: "TD", name: "Tchad" },
  { iso2: "CZ", name: "Tchéquie" },
  { iso2: "TH", name: "Thaïlande" },
  { iso2: "TL", name: "Timor oriental" },
  { iso2: "TG", name: "Togo" },
  { iso2: "TN", name: "Tunisie" },
  { iso2: "TR", name: "Turquie" },
  { iso2: "UA", name: "Ukraine" },
  { iso2: "UY", name: "Uruguay" },
  { iso2: "VE", name: "Venezuela" },
  { iso2: "VN", name: "Vietnam" },
  { iso2: "YE", name: "Yémen" },
  { iso2: "ZM", name: "Zambie" },
  { iso2: "ZW", name: "Zimbabwe" },
];
