// Fichier généré par scripts/gen-zone-countries.ts — ne pas modifier à la main.
export interface ZoneCountry {
  slug: string;
  name: string;
  iso3: string;
}

export const ZONE_COUNTRIES: Record<string, readonly ZoneCountry[]> = {
  "europe": [
    {"slug":"albanie","name":"Albanie","iso3":"ALB"},
    {"slug":"allemagne","name":"Allemagne","iso3":"DEU"},
    {"slug":"armenie","name":"Arménie","iso3":"ARM"},
    {"slug":"autriche","name":"Autriche","iso3":"AUT"},
    {"slug":"azerbaidjan","name":"Azerbaïdjan","iso3":"AZE"},
    {"slug":"belgique","name":"Belgique","iso3":"BEL"},
    {"slug":"bielorussie","name":"Biélorussie","iso3":"BLR"},
    {"slug":"bosnie-herzegovine","name":"Bosnie-Herzégovine","iso3":"BIH"},
    {"slug":"bulgarie","name":"Bulgarie","iso3":"BGR"},
    {"slug":"chypre","name":"Chypre","iso3":"CYP"},
    {"slug":"croatie","name":"Croatie","iso3":"HRV"},
    {"slug":"danemark","name":"Danemark","iso3":"DNK"},
    {"slug":"espagne","name":"Espagne","iso3":"ESP"},
    {"slug":"estonie","name":"Estonie","iso3":"EST"},
    {"slug":"finlande","name":"Finlande","iso3":"FIN"},
    {"slug":"france","name":"France","iso3":"FRA"},
    {"slug":"georgie","name":"Géorgie","iso3":"GEO"},
    {"slug":"grece","name":"Grèce","iso3":"GRC"},
    {"slug":"hongrie","name":"Hongrie","iso3":"HUN"},
    {"slug":"irlande","name":"Irlande","iso3":"IRL"},
    {"slug":"islande","name":"Islande","iso3":"ISL"},
    {"slug":"italie","name":"Italie","iso3":"ITA"},
    {"slug":"kosovo","name":"Kosovo","iso3":"CS-KM"},
    {"slug":"lettonie","name":"Lettonie","iso3":"LVA"},
    {"slug":"lituanie","name":"Lituanie","iso3":"LTU"},
    {"slug":"luxembourg","name":"Luxembourg","iso3":"LUX"},
    {"slug":"macedoine-du-nord","name":"Macédoine du Nord","iso3":"MKD"},
    {"slug":"malte","name":"Malte","iso3":"MLT"},
    {"slug":"moldavie","name":"Moldavie","iso3":"MDA"},
    {"slug":"montenegro","name":"Monténégro","iso3":"MNE"},
    {"slug":"norvege","name":"Norvège","iso3":"NOR"},
    {"slug":"pays-bas","name":"Pays-Bas","iso3":"NLD"},
    {"slug":"pologne","name":"Pologne","iso3":"POL"},
    {"slug":"portugal","name":"Portugal","iso3":"PRT"},
    {"slug":"roumanie","name":"Roumanie","iso3":"ROU"},
    {"slug":"royaume-uni","name":"Royaume-Uni","iso3":"GBR"},
    {"slug":"russie","name":"Russie","iso3":"RUS"},
    {"slug":"serbie","name":"Serbie","iso3":"SRB"},
    {"slug":"slovaquie","name":"Slovaquie","iso3":"SVK"},
    {"slug":"slovenie","name":"Slovénie","iso3":"SVN"},
    {"slug":"suede","name":"Suède","iso3":"SWE"},
    {"slug":"suisse","name":"Suisse","iso3":"CHE"},
    {"slug":"tchequie","name":"Tchéquie","iso3":"CZE"},
    {"slug":"ukraine","name":"Ukraine","iso3":"UKR"},
  ],
  "moyen-orient": [
    {"slug":"arabie-saoudite","name":"Arabie saoudite","iso3":"SAU"},
    {"slug":"egypte","name":"Égypte","iso3":"EGY"},
    {"slug":"emirats-arabes-unis","name":"Émirats arabes unis","iso3":"ARE"},
    {"slug":"irak","name":"Irak","iso3":"IRQ"},
    {"slug":"iran","name":"Iran","iso3":"IRN"},
    {"slug":"israel","name":"Israël","iso3":"ISR"},
    {"slug":"jordanie","name":"Jordanie","iso3":"JOR"},
    {"slug":"koweit","name":"Koweït","iso3":"KWT"},
    {"slug":"liban","name":"Liban","iso3":"LBN"},
    {"slug":"oman","name":"Oman","iso3":"OMN"},
    {"slug":"palestine","name":"Palestine","iso3":"PSE"},
    {"slug":"qatar","name":"Qatar","iso3":"QAT"},
    {"slug":"syrie","name":"Syrie","iso3":"SYR"},
    {"slug":"turquie","name":"Turquie","iso3":"TUR"},
    {"slug":"yemen","name":"Yémen","iso3":"YEM"},
  ],
  "afrique": [
    {"slug":"afrique-du-sud","name":"Afrique du Sud","iso3":"ZAF"},
    {"slug":"algerie","name":"Algérie","iso3":"DZA"},
    {"slug":"angola","name":"Angola","iso3":"AGO"},
    {"slug":"benin","name":"Bénin","iso3":"BEN"},
    {"slug":"botswana","name":"Botswana","iso3":"BWA"},
    {"slug":"burkina-faso","name":"Burkina Faso","iso3":"BFA"},
    {"slug":"burundi","name":"Burundi","iso3":"BDI"},
    {"slug":"cameroun","name":"Cameroun","iso3":"CMR"},
    {"slug":"cote-d-ivoire","name":"Côte d'Ivoire","iso3":"CIV"},
    {"slug":"djibouti","name":"Djibouti","iso3":"DJI"},
    {"slug":"erythree","name":"Érythrée","iso3":"ERI"},
    {"slug":"eswatini","name":"Eswatini","iso3":"SWZ"},
    {"slug":"ethiopie","name":"Éthiopie","iso3":"ETH"},
    {"slug":"gabon","name":"Gabon","iso3":"GAB"},
    {"slug":"gambie","name":"Gambie","iso3":"GMB"},
    {"slug":"ghana","name":"Ghana","iso3":"GHA"},
    {"slug":"guinee","name":"Guinée","iso3":"GIN"},
    {"slug":"guinee-equatoriale","name":"Guinée équatoriale","iso3":"GNQ"},
    {"slug":"guinee-bissau","name":"Guinée-Bissau","iso3":"GNB"},
    {"slug":"kenya","name":"Kenya","iso3":"KEN"},
    {"slug":"lesotho","name":"Lesotho","iso3":"LSO"},
    {"slug":"liberia","name":"Liberia","iso3":"LBR"},
    {"slug":"libye","name":"Libye","iso3":"LBY"},
    {"slug":"madagascar","name":"Madagascar","iso3":"MDG"},
    {"slug":"malawi","name":"Malawi","iso3":"MWI"},
    {"slug":"mali","name":"Mali","iso3":"MLI"},
    {"slug":"maroc","name":"Maroc","iso3":"MAR"},
    {"slug":"mauritanie","name":"Mauritanie","iso3":"MRT"},
    {"slug":"mozambique","name":"Mozambique","iso3":"MOZ"},
    {"slug":"namibie","name":"Namibie","iso3":"NAM"},
    {"slug":"niger","name":"Niger","iso3":"NER"},
    {"slug":"nigeria","name":"Nigeria","iso3":"NGA"},
    {"slug":"ouganda","name":"Ouganda","iso3":"UGA"},
    {"slug":"republique-centrafricaine","name":"République centrafricaine","iso3":"CAF"},
    {"slug":"republique-democratique-du-congo","name":"République démocratique du Congo","iso3":"COD"},
    {"slug":"republique-du-congo","name":"République du Congo","iso3":"COG"},
    {"slug":"rwanda","name":"Rwanda","iso3":"RWA"},
    {"slug":"sahara-occidental","name":"Sahara occidental","iso3":"ESH"},
    {"slug":"senegal","name":"Sénégal","iso3":"SEN"},
    {"slug":"sierra-leone","name":"Sierra Leone","iso3":"SLE"},
    {"slug":"somalie","name":"Somalie","iso3":"SOM"},
    {"slug":"soudan","name":"Soudan","iso3":"SDN"},
    {"slug":"soudan-du-sud","name":"Soudan du Sud","iso3":"SSD"},
    {"slug":"tanzanie","name":"Tanzanie","iso3":"TZA"},
    {"slug":"tchad","name":"Tchad","iso3":"TCD"},
    {"slug":"togo","name":"Togo","iso3":"TGO"},
    {"slug":"tunisie","name":"Tunisie","iso3":"TUN"},
    {"slug":"zambie","name":"Zambie","iso3":"ZMB"},
    {"slug":"zimbabwe","name":"Zimbabwe","iso3":"ZWE"},
  ],
  "indopacifique": [
    {"slug":"brunei","name":"Brunei","iso3":"BRN"},
    {"slug":"cambodge","name":"Cambodge","iso3":"KHM"},
    {"slug":"chine","name":"Chine","iso3":"CHN"},
    {"slug":"coree-du-nord","name":"Corée du Nord","iso3":"PRK"},
    {"slug":"coree-du-sud","name":"Corée du Sud","iso3":"KOR"},
    {"slug":"indonesie","name":"Indonésie","iso3":"IDN"},
    {"slug":"japon","name":"Japon","iso3":"JPN"},
    {"slug":"laos","name":"Laos","iso3":"LAO"},
    {"slug":"malaisie","name":"Malaisie","iso3":"MYS"},
    {"slug":"mongolie","name":"Mongolie","iso3":"MNG"},
    {"slug":"myanmar","name":"Myanmar","iso3":"MMR"},
    {"slug":"philippines","name":"Philippines","iso3":"PHL"},
    {"slug":"taiwan","name":"Taïwan","iso3":"TWN"},
    {"slug":"thailande","name":"Thaïlande","iso3":"THA"},
    {"slug":"timor-oriental","name":"Timor oriental","iso3":"TLS"},
    {"slug":"vietnam","name":"Vietnam","iso3":"VNM"},
  ],
  "amerique-du-sud": [
    {"slug":"argentine","name":"Argentine","iso3":"ARG"},
    {"slug":"bolivie","name":"Bolivie","iso3":"BOL"},
    {"slug":"bresil","name":"Brésil","iso3":"BRA"},
    {"slug":"chili","name":"Chili","iso3":"CHL"},
    {"slug":"colombie","name":"Colombie","iso3":"COL"},
    {"slug":"equateur","name":"Équateur","iso3":"ECU"},
    {"slug":"guyana","name":"Guyana","iso3":"GUY"},
    {"slug":"guyane-francaise","name":"Guyane française","iso3":"GUF"},
    {"slug":"paraguay","name":"Paraguay","iso3":"PRY"},
    {"slug":"perou","name":"Pérou","iso3":"PER"},
    {"slug":"suriname","name":"Suriname","iso3":"SUR"},
    {"slug":"uruguay","name":"Uruguay","iso3":"URY"},
    {"slug":"venezuela","name":"Venezuela","iso3":"VEN"},
  ],
};
